[package]
name = "git-from-scratch"
version = "0.1.0"
authors = ["crash <crash@inventati.org>"]
edition = "2018"

[dependencies]
structopt = { version = "0.2", default-features = false }
rust-ini = "0.13"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
